### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Michael Choi",
  "email": "michael@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Events Index
GET http://localhost:3000/events.json

### Events Create
POST http://localhost:3000/events.json
Content-Type: application/json

{
  "title": "test title",
  "date": "test date",
  "time": "test time",
  "location": "test location",
  "memo": "test memo",
  "user_id": 1
}

### Events Show
GET http://localhost:3000/events/1.json

### Events Update
PATCH http://localhost:3000/events/5.json
Content-Type: application/json

{
  "title": "test title!!",
  "date": "test date!!",
  "time": "test time!!",
  "location": "test location!!",
  "memo": "test memo!!",
  "user_id": 1
}

### Events Destroy
DELETE http://localhost:3000/events/5.json

### Pregnancy Tip API web request
GET https://health.gov/myhealthfinder/api/v3/topicsearch.json?TopicId=30574