@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjIxNjUzMzd9.U4QFMKMQlu63Xcvjx5IfchmD-gobhknrGp8FH94Rmnw

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Michael Choi",
  "email": "michael@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "adalise@test.com",
  "password": "password"
}

### Events Index
GET http://localhost:3000/events.json
Authorization: Bearer {{ jwt }}

### Events Create
POST http://localhost:3000/events.json
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "title": "test title",
  "start": "test start",
  "end": "test end",
  "location": "test location",
  "memo": "test memo"
}

### Events Show
GET http://localhost:3000/events/1.json

### Events Update
PATCH http://localhost:3000/events/2.json
Content-Type: application/json

{
  "title": "Baby shower",
  "start": "2022-09-17 11:00",
  "end": "2022-09-17 14:00",
  "location": "7400 Tuckerman Ln",
  "memo": "",
  "user_id": 1
}

### Events Destroy
DELETE http://localhost:3000/events/5.json

### Checklist Index
GET http://localhost:3000/checklists.json

### Responses Index
GET http://localhost:3000/responses.json

### Responses Create
POST http://localhost:3000/responses.json
Content-Type: application/json

{
  "checklist_id": 7,
  "user_id": 1,
  "quantity": 1,
  "prepared": false
}

### Responses Update
PATCH http://localhost:3000/responses/3.json
Content-Type: application/json

{
  "prepared": false
}


### Pregnancy Tip API web request
GET https://health.gov/myhealthfinder/api/v3/topicsearch.json?TopicId=30574